### ISSUE TITLE
Error running on JDK11 using spring-auto-restdocs-json-doclet-jdk9

### ISSUE THREAD

**Issue by eomeara** [ScaCap/spring-auto-restdocs#268]
Do not know cause of problem but manifested by the following in 2.0.3-SNAPSHOT (similar in 2.0.2):

> Task :jsonDoclet
javadoc: error - fatal error encountered: java.lang.AssertionError
javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.AssertionError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.run(ExtractDocumentationAsJsonDoclet.java:58)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at jdk.compiler/com.sun.tools.javac.util.Log.popDiagnosticHandler(Log.java:481)
        at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.reference(DocCommentParser.java:535)
        at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser$9.parse(DocCommentParser.java:1205)
        at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.inlineTag(DocCommentParser.java:347)
        at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.inlineTag(DocCommentParser.java:311)
        at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.blockContent(DocCommentParser.java:236)
        at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.parse(DocCommentParser.java:131)
        at jdk.compiler/com.sun.tools.javac.parser.LazyDocCommentTable.getCommentTree(LazyDocCommentTable.java:84)
        at jdk.compiler/com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:808)
        at jdk.compiler/com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:820)
        at capital.scalable.restdocs.jsondoclet.MethodDocumentation.fromMethodDoc(MethodDocumentation.java:50)
        at capital.scalable.restdocs.jsondoclet.ClassDocumentation.addMethod(ClassDocumentation.java:68)
        at capital.scalable.restdocs.jsondoclet.ClassDocumentation.lambda$fromClassDoc$0(ClassDocumentation.java:50)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at capital.scalable.restdocs.jsondoclet.ClassDocumentation.fromClassDoc(ClassDocumentation.java:45)
        at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.lambda$run$1(ExtractDocumentationAsJsonDoclet.java:63)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
2 errors

> Task :jsonDoclet FAILED

==========================

From build.gradle:
```
task jsonDoclet(type: Javadoc, dependsOn: compileJava) {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath
    destinationDir = javadocJsonDir
    options.docletpath = configurations.jsondoclet.files.asType(List)
    options.doclet = 'capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet'
    options.memberLevel = JavadocMemberLevel.PACKAGE
}
```
Also
```
	testCompile group: 'capital.scalable', name: 'spring-auto-restdocs-core', version: '2.0.3-SNAPSHOT'
    jsondoclet group: 'capital.scalable', name: 'spring-auto-restdocs-json-doclet-jdk9', version: '2.0.3-SNAPSHOT'
```
Also
```
	id "org.springframework.boot" version "2.1.0.RELEASE"
```

**Comment by fbenz** [comment]
This looks like a bug in the Java doclet code. The following assertion
```
   public void popDiagnosticHandler(DiagnosticHandler h) {
        Assert.check(diagnosticHandler == h);
```
at `com.sun.tools.javac.util.Log.popDiagnosticHandler(Log.java:481)` is failing. The method is called from `com.sun.tools.javac.parser.DocCommentParser.reference(DocCommentParser.java:535)` and the diagnostics are handled there. So it might be a certain condition in your project that is triggering this issue. A quick search did not yield any bug reports referring to a similar issue.

I have compiled and executed the sample programs with Java 11 and did not run into any issues.
