### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by originalrusyn** [ScaCap/spring-auto-restdocs#284]
Please see https://github.com/originalrusyn/bug/tree/StringIndexOutOfBoundsException to reproduce this issue and  https://bugs.openjdk.java.net/browse/JDK-8214775. 
I’ve commit https://github.com/originalrusyn/bug/blob/StringIndexOutOfBoundsException/src/main/resources/javadoc.options generated file too. 
Please try to run "./gradlew clean assemble " multiple times to reproduce this issue. 

A DESCRIPTION OF THE PROBLEM : 
```
javadoc: error - fatal error encountered: java.lang.StringIndexOutOfBoundsException 
javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page 
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) 
for duplicates. Include error messages and the following diagnostic in your report. Thank you. 
java.lang.StringIndexOutOfBoundsException 
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) 
at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603) 
at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) 
at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) 
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) 
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) 
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) 
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) 
at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.run(ExtractDocumentationAsJsonDoclet.java:58)
at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582) 
at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431) 
at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344) 
at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63) 
at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52) 
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 54, length 47 
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319) 
at java.base/java.lang.String.substring(String.java:1874) 
at jdk.compiler/com.sun.tools.javac.tree.DocTreeMaker.splitBody(DocTreeMaker.java:547) 
at jdk.compiler/com.sun.tools.javac.tree.DocTreeMaker.newDocCommentTree(DocTreeMaker.java:215) 
at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.parse(DocCommentParser.java:145) 
at jdk.compiler/com.sun.tools.javac.parser.LazyDocCommentTable.getCommentTree(LazyDocCommentTable.java:84)
at jdk.compiler/com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:808) 
at jdk.compiler/com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:820) 
at capital.scalable.restdocs.jsondoclet.FieldDocumentation.fromFieldDoc(FieldDocumentation.java:45) 
at capital.scalable.restdocs.jsondoclet.ClassDocumentation.addField(ClassDocumentation.java:63) 
at capital.scalable.restdocs.jsondoclet.ClassDocumentation.lambda$fromClassDoc$0(ClassDocumentation.java:47)
at java.base/java.lang.Iterable.forEach(Iterable.java:75) 
at capital.scalable.restdocs.jsondoclet.ClassDocumentation.fromClassDoc(ClassDocumentation.java:45) 
at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.lambda$run$1(ExtractDocumentationAsJsonDoclet.java:63)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) 
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) 
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) 
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) 
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) 
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) 
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) 
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) 
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) 
2 errors 
```

**Comment by jmisur** [comment]
Hi, I tried running it 10 times but build always succeeds. 
Gradle 5.0, Java 11.0.1-open.

Also, we are working with Doclet SDK and it's not much we can do when it crashes inside.

**Comment by m-titov** [comment]
@jmisur 
Could you please remove `parallel()` here https://github.com/ScaCap/spring-auto-restdocs/blob/2.0.3.release/spring-auto-restdocs-json-doclet-jdk9/src/main/java/capital/scalable/restdocs/jsondoclet/ExtractDocumentationAsJsonDoclet.java#L56 ? It seems fix my issue (I've done it and tested locally)
Could you please release fix?

**Comment by jmisur** [comment]
Hey can u try newest 2.0.4-SNAPSHOT to see if it still occurs?

**Comment by m-titov** [comment]
Hi. Don't see today's artifact herehttps://oss.sonatype.org/content/repositories/snapshots/capital/scalable/spring-auto-restdocs-json-doclet-jdk9/2.0.4-SNAPSHOT/

**Comment by jmisur** [comment]
Please try later, it takes some time until it's visible there (dunno why).

**Comment by m-titov** [comment]
@jmisur Could you please force artifact creation somehow? Because I still don't see it https://oss.sonatype.org/content/repositories/snapshots/capital/scalable/spring-auto-restdocs-json-doclet-jdk9/2.0.4-SNAPSHOT/

**Comment by jmisur** [comment]
Hi we have problem with artifact signing. I'll let you know when it's fixed.

**Comment by m-titov** [comment]
@jmisur it works. Please release.

**Comment by jmisur** [comment]
Sorry still problems with signing and I cannot release to Sonatype without it. We'll investigating. Please use snapshots in the meantime.

**Comment by maresja1** [comment]
@jmisur THX for this, it most probably fixed another race condition, with following callstack:

```
error - fatal error encountered: java.lang.AssertionError
javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) FAILED

for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.AssertionError
	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
	at jdk.compiler/com.sun.tools.javac.util.Log.popDiagnosticHandler(Log.java:481)
	at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.reference(DocCommentParser.java:535)
	at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser$9.parse(DocCommentParser.java:1205)
	at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.inlineTag(DocCommentParser.java:347)
	at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.inlineTag(DocCommentParser.java:311)
	at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.blockContent(DocCommentParser.java:236)
	at jdk.compiler/com.sun.tools.javac.parser.DocCommentParser.parse(DocCommentParser.java:131)
	at jdk.compiler/com.sun.tools.javac.parser.LazyDocCommentTable.getCommentTree(LazyDocCommentTable.java:84)
	at jdk.compiler/com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:808)
	at jdk.compiler/com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:820)
	at capital.scalable.restdocs.jsondoclet.MethodDocumentation.fromMethodDoc(MethodDocumentation.java:50)
	at capital.scalable.restdocs.jsondoclet.ClassDocumentation.addMethod(ClassDocumentation.java:68)
	at capital.scalable.restdocs.jsondoclet.ClassDocumentation.lambda$fromClassDoc$0(ClassDocumentation.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at capital.scalable.restdocs.jsondoclet.ClassDocumentation.fromClassDoc(ClassDocumentation.java:45)
2 errors
	at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.lambda$run$1(ExtractDocumentationAsJsonDoclet.java:63)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:1957)
	at java.base/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	at java.base/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet.run(ExtractDocumentationAsJsonDoclet.java:58)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
```
